# Pendahuluan

Tujuan: Menentukan pemain sepakbola terbaik di dunia berdasarkan kriteria-kriteria tertentu

Daftar kriteria penentuan pemain sepakbola terbaik di dunia:

- Konsistensi (C1)
- Goal dan assist (C2)
- Kepemimpinan (C3)
- Prestasi individu (C4)
- Prestasi tim (C5)

---

In [11]:
import numpy as np

# Pembuatan Tabel Perbandingan

In [18]:
total_criteria = 5

matrix = None

In [ ]:
import numpy as np
import ipywidgets as widgets
from IPython.display import display

def create_matrix_form(rows, cols):
    global matrix
    # Generate labels (C1, C2, ...)
    col_labels = [""] + [f"C{i+1}" for i in range(cols)]
    row_labels = [f"C{i+1}" for i in range(rows)]
    
    # Create input fields with diagonal elements pre-filled as 1
    inputs = [[widgets.FloatText(value=(1 if r == c else 0), layout=widgets.Layout(width="50px")) 
               for c in range(cols)] for r in range(rows)]

    # Create the header row (Column Labels)
    header_row = [widgets.Label(value=label, layout=widgets.Layout(width="50px")) for label in col_labels]
    
    # Create rows with Row Labels and Input Fields
    input_rows = []
    for r in range(rows):
        row_widgets = [widgets.Label(value=row_labels[r], layout=widgets.Layout(width="50px"))] + inputs[r]
        input_rows.append(widgets.HBox(row_widgets))

    def get_matrix(_):
        global matrix
        matrix = np.array([[cell.value for cell in row] for row in inputs])
        print("Entered Matrix:")
        print(matrix)

    set_matrix_btn = widgets.Button(description="Set Matrix!")
    set_matrix_btn.on_click(get_matrix)

    display(widgets.HBox(header_row))
    for row in input_rows:
        display(row)
    display(set_matrix_btn)

rows, cols = 5, 5
create_matrix_form(rows, cols)


Button(description='Set Matrix!', style=ButtonStyle())

Entered Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Entered Matrix:
[[1.   5.   2.   5.   3.  ]
 [0.2  1.   2.   3.   0.2 ]
 [0.5  0.5  1.   7.   0.14]
 [0.2  0.33 0.14 1.   0.14]
 [0.33 5.   7.   7.   1.  ]]


Perhitungan total pada masing-masing kolom kriteria

In [28]:
column_sums = np.sum(matrix, axis=0)
print(column_sums)

[ 2.23 11.83 12.14 23.    4.48]


# Proses Normalisasi Data

In [31]:
normalization_matrix = matrix / column_sums

print('Matriks hasil normalisasi')
print(normalization_matrix)

column_sums_normalization_matrix = np.sum(normalization_matrix, axis=1)
print('\nTotal pada tiap-tiap baris kriteria')
print(column_sums_normalization_matrix)

avg_priority_weights = column_sums_normalization_matrix / total_criteria
print('\nNilai rata-rata dari PW (Priority Weight)')
print(avg_priority_weights)

Matriks hasil normalisasi
[[0.44843049 0.42265427 0.16474465 0.2173913  0.66964286]
 [0.0896861  0.08453085 0.16474465 0.13043478 0.04464286]
 [0.22421525 0.04226543 0.08237232 0.30434783 0.03125   ]
 [0.0896861  0.02789518 0.01153213 0.04347826 0.03125   ]
 [0.14798206 0.42265427 0.57660626 0.30434783 0.22321429]]

Total pada tiap-tiap baris kriteria
[1.92286357 0.51403924 0.68445082 0.20384167 1.6748047 ]

Nilai rata-rata dari PW (Priority Weight)
[0.38457271 0.10280785 0.13689016 0.04076833 0.33496094]


# Mengalikan Matriks dengan PW

In [33]:
new_matrix = matrix @ avg_priority_weights

print(new_matrix)

[2.38111677 0.64279991 0.71285331 0.21766862 2.21951866]


In [34]:
val_b = new_matrix / avg_priority_weights
print(val_b)

[6.19159052 6.25244009 5.20748377 5.33915917 6.62620141]


# Menghitung Bobot Prioritas

# Menghitung Nilai $\lambda_{max}$

In [37]:
lambda_max = np.sum(val_b) / total_criteria

print(lambda_max)

5.923374991658529


# Menghitung Nilai Consistency Index (CI)

In [38]:
consistency_index = (lambda_max - total_criteria) / (total_criteria - 1)

print(consistency_index)

0.23084374791463236


# Perhitungan Consistency Ratio

In [40]:
consistency_ratio = consistency_index / 1.12

print(consistency_ratio)

0.20611048920949315


# Menghitung Perbandingan Pasangan untuk Setiap Alternatif/Pilihan pada Tiap Kriteria

# Pengambilan Keputusan