# Pendahuluan

Tujuan: Menentukan pemain sepakbola terbaik di dunia berdasarkan kriteria-kriteria tertentu

Daftar kriteria penentuan pemain sepakbola terbaik di dunia:

- Konsistensi (C1)
- Prestasi tim (C2)
- Goal dan assist (C3)
- Kepemimpinan (C4)
- Prestasi individu (C5)


Pilihan:
1. Jude Bellingham - Real Madrid
2. Erling Haaland - Manchester City
3. Kylian Mbappe - Real Madrid
4. Pedri - Barcelona
5. Vinicius Jr. -  Real Madrid

---

Helper function untuk menampilkan input form pembuatan matriks

In [3]:
import numpy as np
import ipywidgets as widgets
from IPython.display import display

def create_matrix_form(rows, cols):
    # Generate labels (C1, C2, ...)
    col_labels = [""] + [f"C{i+1}" for i in range(cols)]
    row_labels = [f"C{i+1}" for i in range(rows)]
    
    # Create input fields with diagonal elements pre-filled as 1
    inputs = [[widgets.FloatText(value=(1 if r == c else 0), layout=widgets.Layout(width="50px")) 
               for c in range(cols)] for r in range(rows)]

    # Create the header row (Column Labels)
    header_row = [widgets.Label(value=label, layout=widgets.Layout(width="50px")) for label in col_labels]
    
    # Create rows with Row Labels and Input Fields
    input_rows = []
    for r in range(rows):
        row_widgets = [widgets.Label(value=row_labels[r], layout=widgets.Layout(width="50px"))] + inputs[r]
        input_rows.append(widgets.HBox(row_widgets))

    def get_matrix():
        return np.array([[cell.value for cell in row] for row in inputs])
        
    def update_matrix(_):
        """Updates and prints the matrix when the button is clicked."""
        updated_matrix = get_matrix()
        print("Updated Matrix:")
        print(updated_matrix)

    set_matrix_btn = widgets.Button(description="Set Matrix!")
    set_matrix_btn.on_click(update_matrix)

    display(widgets.HBox(header_row))
    for row in input_rows:
        display(row)
    display(set_matrix_btn)
    
    return get_matrix

# Penentuan CR Kriteria

## Pembuatan Tabel Perbandingan

In [4]:
total_criteria = 5

In [5]:
criteria_matrix = create_matrix_form(rows=total_criteria, cols=total_criteria)

Button(description='Set Matrix!', style=ButtonStyle())

Perhitungan total pada masing-masing kolom kriteria

In [6]:
column_sums = np.sum(criteria_matrix(), axis=0)
print(column_sums)

[1. 1. 1. 1. 1.]


## Proses Normalisasi Data

In [7]:
normalization_matrix = criteria_matrix() / column_sums

print('Matriks hasil normalisasi')
print(normalization_matrix)

column_sums_normalization_matrix = np.sum(normalization_matrix, axis=1)
print('\nTotal pada tiap-tiap baris kriteria')
print(column_sums_normalization_matrix)

avg_priority_weights = column_sums_normalization_matrix / total_criteria
print('\nNilai rata-rata dari PW (Priority Weight)')
print(avg_priority_weights)

Matriks hasil normalisasi
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Total pada tiap-tiap baris kriteria
[1. 1. 1. 1. 1.]

Nilai rata-rata dari PW (Priority Weight)
[0.2 0.2 0.2 0.2 0.2]


## Mengalikan Matriks dengan PW

In [8]:
new_matrix = criteria_matrix() @ avg_priority_weights

print(new_matrix)

[0.2 0.2 0.2 0.2 0.2]


In [9]:
val_b = new_matrix / avg_priority_weights
print(val_b)

[1. 1. 1. 1. 1.]


## Menghitung Bobot Prioritas

## Menghitung Nilai $\lambda_{max}$

In [10]:
lambda_max = np.sum(val_b) / total_criteria

print(lambda_max)

1.0


## Menghitung Nilai Consistency Index (CI)

In [11]:
consistency_index = (lambda_max - total_criteria) / (total_criteria - 1)

print(consistency_index)

-1.0


## Perhitungan Consistency Ratio

In [12]:
consistency_ratio = consistency_index / 1.12

print(consistency_ratio)

-0.8928571428571428


# Menghitung Perbandingan Pasangan untuk Setiap Alternatif/Pilihan pada Tiap Kriteria

In [13]:
total_option = 5

## Consistency Ratio (CR) kriteria **Konsistensi**

### Pembuatan Tabel Perbandingan

In [14]:
c1_matrix = create_matrix_form(rows=total_option, cols=total_option)

Button(description='Set Matrix!', style=ButtonStyle())

In [15]:
column_sums_c1 = np.sum(c1_matrix(), axis=0)
print(column_sums_c1)

[1. 1. 1. 1. 1.]


### Proses Normalisasi Data

In [16]:
normalization_matrix_c1 = c1_matrix() / column_sums_c1

print('Matriks hasil normalisasi')
print(normalization_matrix_c1)

column_sums_normalization_matrix_c1 = np.sum(normalization_matrix_c1, axis=1)
print('\nTotal pada tiap-tiap baris kriteria')
print(column_sums_normalization_matrix_c1)

avg_priority_weights_c1 = column_sums_normalization_matrix_c1 / total_option
print('\nNilai rata-rata dari PW (Priority Weight)')
print(avg_priority_weights_c1)

Matriks hasil normalisasi
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Total pada tiap-tiap baris kriteria
[1. 1. 1. 1. 1.]

Nilai rata-rata dari PW (Priority Weight)
[0.2 0.2 0.2 0.2 0.2]


### Mengalikan Matriks dengan PW

In [17]:
new_matrix_c1 = c1_matrix() @ avg_priority_weights_c1

print(new_matrix_c1)

val_b_c1 = new_matrix_c1 / avg_priority_weights_c1
print(val_b_c1)

[0.2 0.2 0.2 0.2 0.2]
[1. 1. 1. 1. 1.]


### Menghitung Bobot Prioritas

### Menghitung Nilai $\lambda_{max}$

In [18]:
lambda_max_c1 = np.sum(val_b_c1) / total_option

print(lambda_max_c1)

1.0


### Menghitung Nilai Consistency Index (CI)

In [19]:
consistency_index_c1 = (lambda_max_c1 - total_option) / (total_option - 1)

print(consistency_index_c1)

-1.0


### Menghitung Nilai Consistency Ratio (CR)

In [20]:
consistency_ratio_c1 = consistency_index_c1 / 1.12

print(consistency_ratio_c1)

-0.8928571428571428


---

## Consistency Ratio (CR) Kriteria **Prestasi Tim**

### Pembuatan Tabel Perbandingan

In [21]:
c2_matrix = create_matrix_form(rows=total_option, cols=total_option)

Button(description='Set Matrix!', style=ButtonStyle())

In [22]:
column_sums_c2 = np.sum(c2_matrix(), axis=0)
print(column_sums_c2)

[1. 1. 1. 1. 1.]


### Proses Normalisasi Data

In [23]:
normalization_matrix_c2 = c2_matrix() / column_sums_c2

print('Matriks hasil normalisasi')
print(normalization_matrix_c2)

column_sums_normalization_matrix_c2 = np.sum(normalization_matrix_c2, axis=1)
print('\nTotal pada tiap-tiap baris kriteria')
print(column_sums_normalization_matrix_c2)

avg_priority_weights_c2 = column_sums_normalization_matrix_c2 / total_option
print('\nNilai rata-rata dari PW (Priority Weight)')
print(avg_priority_weights_c2)

Matriks hasil normalisasi
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Total pada tiap-tiap baris kriteria
[1. 1. 1. 1. 1.]

Nilai rata-rata dari PW (Priority Weight)
[0.2 0.2 0.2 0.2 0.2]


### Mengalikan Matriks dengan PW

In [24]:
new_matrix_c2 = c2_matrix() @ avg_priority_weights_c2

print(new_matrix_c2)

val_b_c2 = new_matrix_c2 / avg_priority_weights_c2
print(val_b_c2)

[0.2 0.2 0.2 0.2 0.2]
[1. 1. 1. 1. 1.]


### Menghitung Bobot Prioritas

### Menghitung Nilai $\lambda_{max}$

In [25]:
lambda_max_c2 = np.sum(val_b_c2) / total_option

print(lambda_max_c2)

1.0


### Menghitung Nilai Consistency Index (CI)

In [26]:
consistency_index_c2 = (lambda_max_c2 - total_option) / (total_option - 1)

print(consistency_index_c2)

-1.0


### Menghitung Nilai Consistency Ratio (CR)

In [27]:
consistency_ratio_c2 = consistency_index_c2 / 1.12

print(consistency_ratio_c2)

-0.8928571428571428


---

## Consistency Ratio (CR) Kriteria **Goal & Assist**

### Pembuatan Tabel Perbandingan

In [76]:
c3_matrix = create_matrix_form(rows=total_option, cols=total_option)

Button(description='Set Matrix!', style=ButtonStyle())

Updated Matrix:
[[1.   5.   6.   7.   2.  ]
 [0.2  1.   3.   5.   0.5 ]
 [0.16 0.33 1.   3.   0.2 ]
 [0.14 0.2  0.3  1.   0.16]
 [0.5  2.   5.   6.   1.  ]]


In [83]:
column_sums_c3 = np.sum(c3_matrix(), axis=0)
print(column_sums_c3)

[ 2.    8.53 15.3  22.    3.86]


### Proses Normalisasi Data

In [84]:
normalization_matrix_c3 = c3_matrix() / column_sums_c3

print('Matriks hasil normalisasi')
print(normalization_matrix_c3)

column_sums_normalization_matrix_c3 = np.sum(normalization_matrix_c3, axis=1)
print('\nTotal pada tiap-tiap baris kriteria')
print(column_sums_normalization_matrix_c3)

avg_priority_weights_c3 = column_sums_normalization_matrix_c3 / total_option
print('\nNilai rata-rata dari PW (Priority Weight)')
print(avg_priority_weights_c3)

Matriks hasil normalisasi
[[0.5        0.58616647 0.39215686 0.31818182 0.51813472]
 [0.1        0.11723329 0.19607843 0.22727273 0.12953368]
 [0.08       0.03868699 0.06535948 0.13636364 0.05181347]
 [0.07       0.02344666 0.01960784 0.04545455 0.04145078]
 [0.25       0.23446659 0.32679739 0.27272727 0.25906736]]

Total pada tiap-tiap baris kriteria
[2.31463987 0.77011813 0.37222357 0.19995982 1.3430586 ]

Nilai rata-rata dari PW (Priority Weight)
[0.46292797 0.15402363 0.07444471 0.03999196 0.26861172]


### Mengalikan Matriks dengan PW

In [85]:
new_matrix_c3 = c3_matrix() @ avg_priority_weights_c3

print(new_matrix_c3)

val_b_c3 = new_matrix_c3 / avg_priority_weights_c3
print(val_b_c3)

[2.49688159 0.80420905 0.37303923 0.2009179  1.42029832]
[5.39367187 5.22133564 5.0109565  5.0239566  5.28755155]


### Menghitung Bobot Prioritas

### Menghitung Nilai $\lambda_{max}$

In [86]:
lambda_max_c3 = np.sum(val_b_c3) / total_option

print(lambda_max_c3)

5.187494432761653


### Menghitung Nilai Consistency Index (CI)

In [87]:
consistency_index_c3 = (lambda_max_c3 - total_option) / (total_option - 1)

print(consistency_index_c3)

0.04687360819041331


### Menghitung Nilai Consistency Ratio (CR)

In [88]:
consistency_ratio_c3 = consistency_index_c3 / 1.12

print(consistency_ratio_c3)

0.04185143588429759


## Consistency Ratio (CR) Kriteria **Kepemimpinan**

### Pembuatan Tabel Perbandingan

In [ ]:
c4_matrix = create_matrix_form(rows=total_option, cols=total_option)

Button(description='Set Matrix!', style=ButtonStyle())

Updated Matrix:
[[1.   3.   4.   7.   9.  ]
 [0.25 1.   0.33 5.   6.  ]
 [0.2  3.   1.   0.2  0.7 ]
 [0.14 0.2  5.   1.   2.  ]
 [0.11 0.16 7.   0.5  1.  ]]
Updated Matrix:
[[1.   3.   4.   5.   7.  ]
 [0.33 1.   0.33 5.   6.  ]
 [0.25 3.   1.   0.2  0.14]
 [0.2  0.2  5.   1.   2.  ]
 [0.14 0.16 7.   0.5  1.  ]]
Updated Matrix:
[[1.   4.   2.   5.   7.  ]
 [0.25 1.   0.33 5.   6.  ]
 [0.5  3.   1.   0.2  0.14]
 [0.2  0.2  5.   1.   2.  ]
 [0.14 0.16 7.   0.5  1.  ]]
Updated Matrix:
[[1.   4.   2.   5.   7.  ]
 [0.25 1.   0.5  3.   5.  ]
 [0.5  2.   1.   0.2  0.14]
 [0.2  0.33 5.   1.   2.  ]
 [0.14 0.2  7.   0.5  1.  ]]
Updated Matrix:
[[1.   4.   2.   5.   6.  ]
 [0.25 1.   0.5  3.   5.  ]
 [0.5  2.   1.   0.2  0.14]
 [0.2  0.33 5.   1.   2.  ]
 [0.16 0.2  7.   0.5  1.  ]]
Updated Matrix:
[[1.   4.   2.   5.   6.  ]
 [0.25 1.   0.5  2.   4.  ]
 [0.5  2.   1.   0.2  0.14]
 [0.2  0.5  5.   1.   3.  ]
 [0.16 0.25 7.   0.33 1.  ]]
Updated Matrix:
[[1.   3.   2.   4.   5.  ]
 [0.33 1.   0.

In [160]:
column_sums_c4 = np.sum(c4_matrix(), axis=0)
print(column_sums_c4)

[2.89 6.16 6.5  6.16 8.5 ]


### Proses Normalisasi Data

In [161]:
normalization_matrix_c4 = c4_matrix() / column_sums_c4

print('Matriks hasil normalisasi')
print(normalization_matrix_c4)

column_sums_normalization_matrix_c4 = np.sum(normalization_matrix_c4, axis=1)
print('\nTotal pada tiap-tiap baris kriteria')
print(column_sums_normalization_matrix_c4)

avg_priority_weights_c4 = column_sums_normalization_matrix_c4 / total_option
print('\nNilai rata-rata dari PW (Priority Weight)')
print(avg_priority_weights_c4)

Matriks hasil normalisasi
[[0.34602076 0.32467532 0.23076923 0.40584416 0.35294118]
 [0.17301038 0.16233766 0.07692308 0.24350649 0.23529412]
 [0.2283737  0.32467532 0.15384615 0.10714286 0.05882353]
 [0.1384083  0.10714286 0.23076923 0.16233766 0.23529412]
 [0.11418685 0.08116883 0.30769231 0.08116883 0.11764706]]

Total pada tiap-tiap baris kriteria
[1.66025065 0.89107173 0.87286157 0.87395217 0.70186388]

Nilai rata-rata dari PW (Priority Weight)
[0.33205013 0.17821435 0.17457231 0.17479043 0.14037278]


### Mengalikan Matriks dengan PW

In [162]:
new_matrix_c4 = c4_matrix() @ avg_priority_weights_c4

print(new_matrix_c4)

val_b_c4 = new_matrix_c4 / avg_priority_weights_c4
print(val_b_c4)

[1.80843171 0.97445677 0.93570217 0.96783598 0.77559634]
[5.4462611  5.46789185 5.35996887 5.5371221  5.52526179]


### Menghitung Bobot Prioritas

### Menghitung Nilai $\lambda_{max}$

In [163]:
lambda_max_c4 = np.sum(val_b_c4) / total_option

print(lambda_max_c4)

5.467301144110351


### Menghitung Nilai Consistency Index (CI)

In [164]:
consistency_index_c4 = (lambda_max_c4 - total_option) / (total_option - 1)

print(consistency_index_c4)

0.1168252860275878


### Menghitung Nilai Consistency Ratio (CR)

In [165]:
consistency_ratio_c4 = consistency_index_c4 / 1.12

print(consistency_ratio_c4)

0.10430829109606052


---

## Consistency Ratio (CR) Kriteria **Prestasi Individu**

### Pembuatan Tabel Perbandingan

In [ ]:
c5_matrix = create_matrix_form(rows=total_option, cols=total_option)

Button(description='Set Matrix!', style=ButtonStyle())

Updated Matrix:
[[1.   3.   5.   7.   6.  ]
 [0.33 1.   3.   6.   5.  ]
 [0.2  0.33 1.   6.   4.  ]
 [0.14 0.16 0.16 1.   0.2 ]
 [0.16 0.2  0.25 5.   1.  ]]
Updated Matrix:
[[1.   3.   5.   9.   6.  ]
 [0.33 1.   3.   6.   5.  ]
 [0.2  0.33 1.   6.   4.  ]
 [0.19 0.16 0.16 1.   0.2 ]
 [0.16 0.2  0.25 5.   1.  ]]
Updated Matrix:
[[1.   3.   5.   7.   6.  ]
 [0.33 1.   3.   7.   5.  ]
 [0.2  0.33 1.   6.   4.  ]
 [0.14 0.14 0.16 1.   0.2 ]
 [0.16 0.2  0.25 5.   1.  ]]
Updated Matrix:
[[1.   3.   5.   7.   6.  ]
 [0.33 1.   3.   7.   5.  ]
 [0.2  0.33 1.   6.   2.  ]
 [0.14 0.14 0.16 1.   0.2 ]
 [0.16 0.2  0.5  5.   1.  ]]


In [185]:
column_sums_c5 = np.sum(c5_matrix(), axis=0)
print(column_sums_c5)

[ 1.83  4.67  9.66 26.   14.2 ]


### Proses Normalisasi Data

In [186]:
normalization_matrix_c5 = c5_matrix() / column_sums_c5

print('Matriks hasil normalisasi')
print(normalization_matrix_c5)

column_sums_normalization_matrix_c5 = np.sum(normalization_matrix_c5, axis=1)
print('\nTotal pada tiap-tiap baris kriteria')
print(column_sums_normalization_matrix_c5)

avg_priority_weights_c5 = column_sums_normalization_matrix_c5 / total_option
print('\nNilai rata-rata dari PW (Priority Weight)')
print(avg_priority_weights_c5)

Matriks hasil normalisasi
[[0.54644809 0.64239829 0.51759834 0.26923077 0.42253521]
 [0.18032787 0.21413276 0.31055901 0.26923077 0.35211268]
 [0.10928962 0.07066381 0.10351967 0.23076923 0.14084507]
 [0.07650273 0.02997859 0.01656315 0.03846154 0.01408451]
 [0.08743169 0.04282655 0.05175983 0.19230769 0.07042254]]

Total pada tiap-tiap baris kriteria
[2.3982107  1.32636308 0.6550874  0.17559051 0.44474831]

Nilai rata-rata dari PW (Priority Weight)
[0.47964214 0.26527262 0.13101748 0.0351181  0.08894966]


### Mengalikan Matriks dengan PW

In [187]:
new_matrix_c5 = c5_matrix() @ avg_priority_weights_c5

print(new_matrix_c5)

val_b_c5 = new_matrix_c5 / avg_priority_weights_c5
print(val_b_c5)

[2.71007207 1.50718199 0.70309381 0.1781589  0.45984618]
[5.65019595 5.68163426 5.36641225 5.07313567 5.16973499]


### Menghitung Bobot Prioritas

### Menghitung Nilai $\lambda_{max}$

In [188]:
lambda_max_c5 = np.sum(val_b_c5) / total_option

print(lambda_max_c5)

5.388222623461261


### Menghitung Nilai Consistency Index (CI)

In [189]:
consistency_index_c5 = (lambda_max_c5 - total_option) / (total_option - 1)

print(consistency_index_c5)

0.09705565586531528


### Menghitung Nilai Consistency Ratio (CR)

In [190]:
consistency_ratio_c5 = consistency_index_c5 / 1.12

print(consistency_ratio_c5)

0.08665683559403149


# Pengambilan Keputusan