# Pendahuluan

Tujuan: Menentukan pemain sepakbola terbaik di dunia berdasarkan kriteria-kriteria tertentu

Daftar kriteria penentuan pemain sepakbola terbaik di dunia:

- Konsistensi (C1)
- Prestasi tim (C2)
- Goal dan assist (C3)
- Kepemimpinan (C4)
- Prestasi individu (C5)


Pilihan:
1. Jude Bellingham - Real Madrid
2. Erling Haaland - Manchester City
3. Kylian Mbappe - Real Madrid
4. Pedri - Barcelona
5. Vinicius Jr. -  Real Madrid

---

In [11]:
import numpy as np

Helper function untuk menampilkan input form pembuatan matriks

In [ ]:
import numpy as np
import ipywidgets as widgets
from IPython.display import display

def create_matrix_form(rows, cols):
    # Generate labels (C1, C2, ...)
    col_labels = [""] + [f"C{i+1}" for i in range(cols)]
    row_labels = [f"C{i+1}" for i in range(rows)]
    
    # Create input fields with diagonal elements pre-filled as 1
    inputs = [[widgets.FloatText(value=(1 if r == c else 0), layout=widgets.Layout(width="50px")) 
               for c in range(cols)] for r in range(rows)]

    # Create the header row (Column Labels)
    header_row = [widgets.Label(value=label, layout=widgets.Layout(width="50px")) for label in col_labels]
    
    # Create rows with Row Labels and Input Fields
    input_rows = []
    for r in range(rows):
        row_widgets = [widgets.Label(value=row_labels[r], layout=widgets.Layout(width="50px"))] + inputs[r]
        input_rows.append(widgets.HBox(row_widgets))

    def get_matrix():
        return np.array([[cell.value for cell in row] for row in inputs])
        
    def update_matrix(_):
        """Updates and prints the matrix when the button is clicked."""
        updated_matrix = get_matrix()
        print("Updated Matrix:")
        print(updated_matrix)

    set_matrix_btn = widgets.Button(description="Set Matrix!")
    set_matrix_btn.on_click(update_matrix)

    display(widgets.HBox(header_row))
    for row in input_rows:
        display(row)
    display(set_matrix_btn)
    
    return get_matrix

# Penentuan CR Kriteria

## Pembuatan Tabel Perbandingan

In [ ]:
total_criteria = 5

In [179]:
criteria_matrix = create_matrix_form(rows=total_criteria, cols=total_criteria)

Button(description='Set Matrix!', style=ButtonStyle())

Updated Matrix:
[[1.   3.   0.5  5.   0.33]
 [0.33 1.   0.2  0.33 0.2 ]
 [2.   5.   1.   3.   0.33]
 [0.2  3.   0.33 1.   0.14]
 [3.   5.   3.   7.   1.  ]]


Perhitungan total pada masing-masing kolom kriteria

In [183]:
column_sums = np.sum(criteria_matrix(), axis=0)
print(column_sums)

[ 6.53 17.    5.03 16.33  2.  ]


## Proses Normalisasi Data

In [184]:
normalization_matrix = criteria_matrix() / column_sums

print('Matriks hasil normalisasi')
print(normalization_matrix)

column_sums_normalization_matrix = np.sum(normalization_matrix, axis=1)
print('\nTotal pada tiap-tiap baris kriteria')
print(column_sums_normalization_matrix)

avg_priority_weights = column_sums_normalization_matrix / total_criteria
print('\nNilai rata-rata dari PW (Priority Weight)')
print(avg_priority_weights)

Matriks hasil normalisasi
[[0.15313936 0.17647059 0.09940358 0.30618494 0.165     ]
 [0.05053599 0.05882353 0.03976143 0.02020821 0.1       ]
 [0.30627871 0.29411765 0.19880716 0.18371096 0.165     ]
 [0.03062787 0.17647059 0.06560636 0.06123699 0.07      ]
 [0.45941807 0.29411765 0.59642147 0.42865891 0.5       ]]

Total pada tiap-tiap baris kriteria
[0.90019846 0.26932915 1.14791448 0.40394181 2.2786161 ]

Nilai rata-rata dari PW (Priority Weight)
[0.18003969 0.05386583 0.2295829  0.08078836 0.45572322]


## Mengalikan Matriks dengan PW

In [185]:
new_matrix = criteria_matrix() @ avg_priority_weights

print(new_matrix)

[1.0107591  0.27700031 1.25174518 0.4179574  2.51943867]


In [186]:
val_b = new_matrix / avg_priority_weights
print(val_b)

[5.61409039 5.14241231 5.452258   5.17348527 5.52844042]


## Menghitung Bobot Prioritas

## Menghitung Nilai $\lambda_{max}$

In [187]:
lambda_max = np.sum(val_b) / total_criteria

print(lambda_max)

5.382137277934705


## Menghitung Nilai Consistency Index (CI)

In [188]:
consistency_index = (lambda_max - total_criteria) / (total_criteria - 1)

print(consistency_index)

0.09553431948367619


## Perhitungan Consistency Ratio

In [189]:
consistency_ratio = consistency_index / 1.12

print(consistency_ratio)

0.08529849953899658


# Menghitung Perbandingan Pasangan untuk Setiap Alternatif/Pilihan pada Tiap Kriteria

In [219]:
total_option = 5

## Consistency Ratio (CR) kriteria **Konsistensi**

### Pembuatan Tabel Perbandingan

In [ ]:
c1_matrix = create_matrix_form(rows=total_option, cols=total_option)

Button(description='Set Matrix!', style=ButtonStyle())

Updated Matrix:
[[1.   0.5  3.   7.   5.  ]
 [2.   1.   3.   7.   5.  ]
 [0.33 0.33 1.   5.   2.  ]
 [0.14 0.14 0.2  1.   0.2 ]
 [0.2  0.2  0.5  5.   1.  ]]
Updated Matrix:
[[1.   0.5  3.   7.   5.  ]
 [2.   1.   3.   9.   5.  ]
 [0.33 0.33 1.   5.   2.  ]
 [0.14 0.11 0.2  1.   0.2 ]
 [0.2  0.2  0.5  5.   1.  ]]


In [213]:
column_sums_c1 = np.sum(c1_matrix(), axis=0)
print(column_sums_c1)

[ 3.67  2.14  7.7  27.   13.2 ]


### Proses Normalisasi Data

In [225]:
normalization_matrix_c1 = c1_matrix() / column_sums_c1

print('Matriks hasil normalisasi')
print(normalization_matrix_c1)

column_sums_normalization_matrix_c1 = np.sum(normalization_matrix_c1, axis=1)
print('\nTotal pada tiap-tiap baris kriteria')
print(column_sums_normalization_matrix_c1)

avg_priority_weights_c1 = column_sums_normalization_matrix_c1 / total_option
print('\nNilai rata-rata dari PW (Priority Weight)')
print(avg_priority_weights_c1)

Matriks hasil normalisasi
[[0.27247956 0.23364486 0.38961039 0.25925926 0.37878788]
 [0.54495913 0.46728972 0.38961039 0.33333333 0.37878788]
 [0.08991826 0.15420561 0.12987013 0.18518519 0.15151515]
 [0.03814714 0.05140187 0.02597403 0.03703704 0.01515152]
 [0.05449591 0.09345794 0.06493506 0.18518519 0.07575758]]

Total pada tiap-tiap baris kriteria
[1.53378195 2.11398045 0.71069433 0.16771159 0.47383168]

Nilai rata-rata dari PW (Priority Weight)
[0.30675639 0.42279609 0.14213887 0.03354232 0.09476634]


### Mengalikan Matriks dengan PW

In [221]:
new_matrix_c1 = c1_matrix() @ avg_priority_weights_c1

print(new_matrix_c1)

val_b_c1 = new_matrix_c1 / avg_priority_weights_c1
print(val_b_c1)

[1.65319894 2.23843801 0.74013544 0.17037682 0.47945785]
[5.38928932 5.29436781 5.20712923 5.07945891 5.05936886]


### Menghitung Bobot Prioritas

### Menghitung Nilai $\lambda_{max}$

In [222]:
lambda_max_c1 = np.sum(val_b_c1) / total_option

print(lambda_max_c1)

5.2059228239114095


### Menghitung Nilai Consistency Index (CI)

In [223]:
consistency_index_c1 = (lambda_max_c1 - total_option) / (total_option - 1)

print(consistency_index_c1)

0.05148070597785237


### Menghitung Nilai Consistency Ratio (CR)

In [224]:
consistency_ratio_c1 = consistency_index_c1 / 1.12

print(consistency_ratio_c1)

0.0459649160516539


---

## Consistency Ratio (CR) Kriteria **Prestasi Tim**

### Pembuatan Tabel Perbandingan

In [227]:
c2_matrix = create_matrix_form(rows=total_option, cols=total_option)

Button(description='Set Matrix!', style=ButtonStyle())

Updated Matrix:
[[1.   5.   6.   7.   2.  ]
 [0.2  1.   3.   5.   0.5 ]
 [0.16 0.33 1.   3.   0.2 ]
 [0.14 0.2  0.3  1.   0.16]
 [0.5  2.   5.   6.   1.  ]]


In [228]:
column_sums_c2 = np.sum(c2_matrix(), axis=0)
print(column_sums_c2)

[ 2.    8.53 15.3  22.    3.86]


### Proses Normalisasi Data

In [229]:
normalization_matrix_c2 = c2_matrix() / column_sums_c2

print('Matriks hasil normalisasi')
print(normalization_matrix_c2)

column_sums_normalization_matrix_c2 = np.sum(normalization_matrix_c2, axis=1)
print('\nTotal pada tiap-tiap baris kriteria')
print(column_sums_normalization_matrix_c2)

avg_priority_weights_c2 = column_sums_normalization_matrix_c2 / total_option
print('\nNilai rata-rata dari PW (Priority Weight)')
print(avg_priority_weights_c2)

Matriks hasil normalisasi
[[0.5        0.58616647 0.39215686 0.31818182 0.51813472]
 [0.1        0.11723329 0.19607843 0.22727273 0.12953368]
 [0.08       0.03868699 0.06535948 0.13636364 0.05181347]
 [0.07       0.02344666 0.01960784 0.04545455 0.04145078]
 [0.25       0.23446659 0.32679739 0.27272727 0.25906736]]

Total pada tiap-tiap baris kriteria
[2.31463987 0.77011813 0.37222357 0.19995982 1.3430586 ]

Nilai rata-rata dari PW (Priority Weight)
[0.46292797 0.15402363 0.07444471 0.03999196 0.26861172]


### Mengalikan Matriks dengan PW

In [234]:
new_matrix_c2 = c2_matrix() @ avg_priority_weights_c2

print(new_matrix_c2)

val_b_c2 = new_matrix_c2 / avg_priority_weights_c2
print(val_b_c2)

[2.49688159 0.80420905 0.37303923 0.2009179  1.42029832]
[5.39367187 5.22133564 5.0109565  5.0239566  5.28755155]


### Menghitung Bobot Prioritas

### Menghitung Nilai $\lambda_{max}$

In [231]:
lambda_max_c2 = np.sum(val_b_c2) / total_option

print(lambda_max_c2)

5.187494432761653


### Menghitung Nilai Consistency Index (CI)

In [232]:
consistency_index_c2 = (lambda_max_c2 - total_option) / (total_option - 1)

print(consistency_index_c2)

0.04687360819041331


### Menghitung Nilai Consistency Ratio (CR)

In [233]:
consistency_ratio_c2 = consistency_index_c2 / 1.12

print(consistency_ratio_c2)

0.04185143588429759


## Consistency Ratio (CR) Kriteria **Goal & Assist**

### Pembuatan Tabel Perbandingan

In [235]:
c3_matrix = create_matrix_form(rows=total_option, cols=total_option)

Button(description='Set Matrix!', style=ButtonStyle())

Updated Matrix:
[[1.    0.14  0.16  3.    0.5  ]
 [7.    1.    2.    8.    4.   ]
 [6.    0.5   1.    5.    3.   ]
 [0.33  0.125 0.2   1.    0.2  ]
 [2.    0.25  0.33  5.    1.   ]]


In [236]:
column_sums_c3 = np.sum(c3_matrix(), axis=0)
print(column_sums_c3)

[16.33   2.015  3.69  22.     8.7  ]


### Proses Normalisasi Data

In [237]:
normalization_matrix_c3 = c3_matrix() / column_sums_c3

print('Matriks hasil normalisasi')
print(normalization_matrix_c3)

column_sums_normalization_matrix_c3 = np.sum(normalization_matrix_c3, axis=1)
print('\nTotal pada tiap-tiap baris kriteria')
print(column_sums_normalization_matrix_c3)

avg_priority_weights_c3 = column_sums_normalization_matrix_c3 / total_option
print('\nNilai rata-rata dari PW (Priority Weight)')
print(avg_priority_weights_c3)

Matriks hasil normalisasi
[[0.06123699 0.06947891 0.04336043 0.13636364 0.05747126]
 [0.42865891 0.49627792 0.54200542 0.36363636 0.45977011]
 [0.36742192 0.24813896 0.27100271 0.22727273 0.34482759]
 [0.02020821 0.06203474 0.05420054 0.04545455 0.02298851]
 [0.12247397 0.12406948 0.08943089 0.22727273 0.11494253]]

Total pada tiap-tiap baris kriteria
[0.36791123 2.29034872 1.4586639  0.20488654 0.6781896 ]

Nilai rata-rata dari PW (Priority Weight)
[0.07358225 0.45806974 0.29173278 0.04097731 0.13563792]


### Mengalikan Matriks dengan PW

In [238]:
new_matrix_c3 = c3_matrix() @ avg_priority_weights_c3

print(new_matrix_c3)

val_b_c3 = new_matrix_c3 / avg_priority_weights_c3
print(val_b_c3)

[0.37514014 2.42698117 1.57406143 0.20799231 0.6984782 ]
[5.09824257 5.2982787  5.39555899 5.07579241 5.14957912]


### Menghitung Bobot Prioritas

### Menghitung Nilai $\lambda_{max}$

In [239]:
lambda_max_c3 = np.sum(val_b_c3) / total_option

print(lambda_max_c3)

5.203490359068052


### Menghitung Nilai Consistency Index (CI)

In [240]:
consistency_index_c3 = (lambda_max_c3 - total_option) / (total_option - 1)

print(consistency_index_c3)

0.05087258976701303


### Menghitung Nilai Consistency Ratio (CR)

In [241]:
consistency_ratio_c3 = consistency_index_c3 / 1.12

print(consistency_ratio_c3)

0.04542195514911877


## Consistency Ratio (CR) Kriteria **Kepemimpinan**

### Pembuatan Tabel Perbandingan

### Proses Normalisasi Data

### Mengalikan Matriks dengan PW

### Menghitung Bobot Prioritas

### Menghitung Nilai $\lambda_{max}$

### Menghitung Nilai Consistency Index (CI)

### Menghitung Nilai Consistency Ratio (CR)

## Consistency Ratio (CR) Kriteria **Prestasi Individu**

### Pembuatan Tabel Perbandingan

### Proses Normalisasi Data

### Mengalikan Matriks dengan PW

### Menghitung Bobot Prioritas

### Menghitung Nilai $\lambda_{max}$

### Menghitung Nilai Consistency Index (CI)

### Menghitung Nilai Consistency Ratio (CR)

# Pengambilan Keputusan