# Pendahuluan

Tujuan: Menentukan pemain sepakbola terbaik di dunia berdasarkan kriteria-kriteria tertentu

Daftar kriteria penentuan pemain sepakbola terbaik di dunia:

- Konsistensi (C1)
- Prestasi tim (C2)
- Goal dan assist (C3)
- Kepemimpinan (C4)
- Prestasi individu (C5)


Pilihan:
1. Jude Bellingham - Real Madrid
2. Erling Haaland - Manchester City
3. Pedri - Barcelona
4. Vinicius Jr. -  Real Madrid

---

In [11]:
import numpy as np

Helper function untuk menampilkan input form pembuatan matriks

In [ ]:
import numpy as np
import ipywidgets as widgets
from IPython.display import display

def create_matrix_form(rows, cols):
    # Generate labels (C1, C2, ...)
    col_labels = [""] + [f"C{i+1}" for i in range(cols)]
    row_labels = [f"C{i+1}" for i in range(rows)]
    
    # Create input fields with diagonal elements pre-filled as 1
    inputs = [[widgets.FloatText(value=(1 if r == c else 0), layout=widgets.Layout(width="50px")) 
               for c in range(cols)] for r in range(rows)]

    # Create the header row (Column Labels)
    header_row = [widgets.Label(value=label, layout=widgets.Layout(width="50px")) for label in col_labels]
    
    # Create rows with Row Labels and Input Fields
    input_rows = []
    for r in range(rows):
        row_widgets = [widgets.Label(value=row_labels[r], layout=widgets.Layout(width="50px"))] + inputs[r]
        input_rows.append(widgets.HBox(row_widgets))

    def get_matrix():
        return np.array([[cell.value for cell in row] for row in inputs])
        
    def update_matrix(_):
        """Updates and prints the matrix when the button is clicked."""
        updated_matrix = get_matrix()
        print("Updated Matrix:")
        print(updated_matrix)

    set_matrix_btn = widgets.Button(description="Set Matrix!")
    set_matrix_btn.on_click(update_matrix)

    display(widgets.HBox(header_row))
    for row in input_rows:
        display(row)
    display(set_matrix_btn)
    
    return get_matrix

# Penentuan CR Kriteria

## Pembuatan Tabel Perbandingan

In [ ]:
total_criteria = 5

In [179]:
criteria_matrix = create_matrix_form(rows=total_criteria, cols=total_criteria)

Button(description='Set Matrix!', style=ButtonStyle())

Updated Matrix:
[[1.   3.   0.5  5.   0.33]
 [0.33 1.   0.2  0.33 0.2 ]
 [2.   5.   1.   3.   0.33]
 [0.2  3.   0.33 1.   0.14]
 [3.   5.   3.   7.   1.  ]]


Perhitungan total pada masing-masing kolom kriteria

In [183]:
column_sums = np.sum(criteria_matrix(), axis=0)
print(column_sums)

[ 6.53 17.    5.03 16.33  2.  ]


## Proses Normalisasi Data

In [184]:
normalization_matrix = criteria_matrix() / column_sums

print('Matriks hasil normalisasi')
print(normalization_matrix)

column_sums_normalization_matrix = np.sum(normalization_matrix, axis=1)
print('\nTotal pada tiap-tiap baris kriteria')
print(column_sums_normalization_matrix)

avg_priority_weights = column_sums_normalization_matrix / total_criteria
print('\nNilai rata-rata dari PW (Priority Weight)')
print(avg_priority_weights)

Matriks hasil normalisasi
[[0.15313936 0.17647059 0.09940358 0.30618494 0.165     ]
 [0.05053599 0.05882353 0.03976143 0.02020821 0.1       ]
 [0.30627871 0.29411765 0.19880716 0.18371096 0.165     ]
 [0.03062787 0.17647059 0.06560636 0.06123699 0.07      ]
 [0.45941807 0.29411765 0.59642147 0.42865891 0.5       ]]

Total pada tiap-tiap baris kriteria
[0.90019846 0.26932915 1.14791448 0.40394181 2.2786161 ]

Nilai rata-rata dari PW (Priority Weight)
[0.18003969 0.05386583 0.2295829  0.08078836 0.45572322]


## Mengalikan Matriks dengan PW

In [185]:
new_matrix = criteria_matrix() @ avg_priority_weights

print(new_matrix)

[1.0107591  0.27700031 1.25174518 0.4179574  2.51943867]


In [186]:
val_b = new_matrix / avg_priority_weights
print(val_b)

[5.61409039 5.14241231 5.452258   5.17348527 5.52844042]


## Menghitung Bobot Prioritas

## Menghitung Nilai $\lambda_{max}$

In [187]:
lambda_max = np.sum(val_b) / total_criteria

print(lambda_max)

5.382137277934705


## Menghitung Nilai Consistency Index (CI)

In [188]:
consistency_index = (lambda_max - total_criteria) / (total_criteria - 1)

print(consistency_index)

0.09553431948367619


## Perhitungan Consistency Ratio

In [189]:
consistency_ratio = consistency_index / 1.12

print(consistency_ratio)

0.08529849953899658


# Menghitung Perbandingan Pasangan untuk Setiap Alternatif/Pilihan pada Tiap Kriteria

In [219]:
total_option = 5

## Consistency Ratio (CR) kriteria **Konsistensi**

### Pembuatan Tabel Perbandingan

In [ ]:
c1_matrix = create_matrix_form(rows=total_option, cols=total_option)

Button(description='Set Matrix!', style=ButtonStyle())

Updated Matrix:
[[1.   0.5  3.   7.   5.  ]
 [2.   1.   3.   7.   5.  ]
 [0.33 0.33 1.   5.   2.  ]
 [0.14 0.14 0.2  1.   0.2 ]
 [0.2  0.2  0.5  5.   1.  ]]
Updated Matrix:
[[1.   0.5  3.   7.   5.  ]
 [2.   1.   3.   9.   5.  ]
 [0.33 0.33 1.   5.   2.  ]
 [0.14 0.11 0.2  1.   0.2 ]
 [0.2  0.2  0.5  5.   1.  ]]


In [213]:
column_sums_c1 = np.sum(c1_matrix(), axis=0)
print(column_sums_c1)

[ 3.67  2.14  7.7  27.   13.2 ]


### Proses Normalisasi Data

In [214]:
normalization_matrix_c1 = c1_matrix() / column_sums

print('Matriks hasil normalisasi')
print(normalization_matrix_c1)

column_sums_normalization_matrix_c1 = np.sum(normalization_matrix_c1, axis=1)
print('\nTotal pada tiap-tiap baris kriteria')
print(column_sums_normalization_matrix_c1)

avg_priority_weights_c1 = column_sums_normalization_matrix_c1 / total_criteria
print('\nNilai rata-rata dari PW (Priority Weight)')
print(avg_priority_weights_c1)

Matriks hasil normalisasi
[[0.15313936 0.02941176 0.59642147 0.42865891 2.5       ]
 [0.30627871 0.05882353 0.59642147 0.55113288 2.5       ]
 [0.05053599 0.01941176 0.19880716 0.30618494 1.        ]
 [0.02143951 0.00647059 0.03976143 0.06123699 0.1       ]
 [0.03062787 0.01176471 0.09940358 0.30618494 0.5       ]]

Total pada tiap-tiap baris kriteria
[3.7076315  4.0126566  1.57493985 0.22890852 0.94798109]

Nilai rata-rata dari PW (Priority Weight)
[0.7415263  0.80253132 0.31498797 0.0457817  0.18959622]


### Mengalikan Matriks dengan PW

In [215]:
new_matrix_c1 = c1_matrix() @ avg_priority_weights_c1

print(new_matrix_c1)

val_b_c1 = new_matrix_c1 / avg_priority_weights_c1
print(val_b_c1)

[3.35620888 4.59056425 1.43262794 0.33879067 0.88481024]
[4.52608206 5.72010604 4.54819891 7.40013244 4.66681378]


### Menghitung Bobot Prioritas

### Menghitung Nilai $\lambda_{max}$

In [216]:
lambda_max_c1 = np.sum(val_b_c1) / total_option

print(lambda_max_c1)

5.372266644099153


### Menghitung Nilai Consistency Index (CI)

In [217]:
consistency_index_c1 = (lambda_max_c1 - total_option) / (total_option - 1)

print(consistency_index_c1)

0.09306666102478833


### Menghitung Nilai Consistency Ratio (CR)

In [218]:
consistency_ratio_c1 = consistency_index_c1 / 1.12

print(consistency_ratio_c1)

0.08309523305784672


## Consistency Ratio (CR) Kriteria **Prestasi Tim**

## Consistency Ratio (CR) Kriteria **Goal & Assist**

## Consistency Ratio (CR) Kriteria **Kepemimpinan**

## Consistency Ratio (CR) Kriteria **Prestasi Individu**

# Pengambilan Keputusan