# Pendahuluan

Tujuan: Menentukan pemain sepakbola terbaik di dunia berdasarkan kriteria-kriteria tertentu

Daftar kriteria penentuan pemain sepakbola terbaik di dunia:

- Konsistensi (C1)
- Prestasi tim (C2)
- Goal dan assist (C3)
- Kepemimpinan (C4)
- Prestasi individu (C5)

---

In [11]:
import numpy as np

# Penentuan CR Kriteria

## Pembuatan Tabel Perbandingan

In [18]:
total_criteria = 5

matrix = None

In [161]:
import numpy as np
import ipywidgets as widgets
from IPython.display import display

def create_matrix_form(rows, cols):
    global matrix
    # Generate labels (C1, C2, ...)
    col_labels = [""] + [f"C{i+1}" for i in range(cols)]
    row_labels = [f"C{i+1}" for i in range(rows)]
    
    # Create input fields with diagonal elements pre-filled as 1
    inputs = [[widgets.FloatText(value=(1 if r == c else 0), layout=widgets.Layout(width="50px")) 
               for c in range(cols)] for r in range(rows)]

    # Create the header row (Column Labels)
    header_row = [widgets.Label(value=label, layout=widgets.Layout(width="50px")) for label in col_labels]
    
    # Create rows with Row Labels and Input Fields
    input_rows = []
    for r in range(rows):
        row_widgets = [widgets.Label(value=row_labels[r], layout=widgets.Layout(width="50px"))] + inputs[r]
        input_rows.append(widgets.HBox(row_widgets))

    def get_matrix(_):
        global matrix
        matrix = np.array([[cell.value for cell in row] for row in inputs])
        print("Entered Matrix:")
        print(matrix)

    set_matrix_btn = widgets.Button(description="Set Matrix!")
    set_matrix_btn.on_click(get_matrix)

    display(widgets.HBox(header_row))
    for row in input_rows:
        display(row)
    display(set_matrix_btn)

rows, cols = total_criteria, total_criteria
create_matrix_form(rows, cols)


Button(description='Set Matrix!', style=ButtonStyle())

Entered Matrix:
[[1.   3.   0.5  5.   0.33]
 [0.33 1.   0.2  0.33 0.2 ]
 [2.   5.   1.   3.   0.33]
 [0.2  3.   0.33 1.   0.14]
 [3.   5.   3.   7.   1.  ]]


Perhitungan total pada masing-masing kolom kriteria

In [162]:
column_sums = np.sum(matrix, axis=0)
print(column_sums)

[ 6.53 17.    5.03 16.33  2.  ]


## Proses Normalisasi Data

In [163]:
normalization_matrix = matrix / column_sums

print('Matriks hasil normalisasi')
print(normalization_matrix)

column_sums_normalization_matrix = np.sum(normalization_matrix, axis=1)
print('\nTotal pada tiap-tiap baris kriteria')
print(column_sums_normalization_matrix)

avg_priority_weights = column_sums_normalization_matrix / total_criteria
print('\nNilai rata-rata dari PW (Priority Weight)')
print(avg_priority_weights)

Matriks hasil normalisasi
[[0.15313936 0.17647059 0.09940358 0.30618494 0.165     ]
 [0.05053599 0.05882353 0.03976143 0.02020821 0.1       ]
 [0.30627871 0.29411765 0.19880716 0.18371096 0.165     ]
 [0.03062787 0.17647059 0.06560636 0.06123699 0.07      ]
 [0.45941807 0.29411765 0.59642147 0.42865891 0.5       ]]

Total pada tiap-tiap baris kriteria
[0.90019846 0.26932915 1.14791448 0.40394181 2.2786161 ]

Nilai rata-rata dari PW (Priority Weight)
[0.18003969 0.05386583 0.2295829  0.08078836 0.45572322]


## Mengalikan Matriks dengan PW

In [164]:
new_matrix = matrix @ avg_priority_weights

print(new_matrix)

[1.0107591  0.27700031 1.25174518 0.4179574  2.51943867]


In [165]:
val_b = new_matrix / avg_priority_weights
print(val_b)

[5.61409039 5.14241231 5.452258   5.17348527 5.52844042]


## Menghitung Bobot Prioritas

## Menghitung Nilai $\lambda_{max}$

In [166]:
lambda_max = np.sum(val_b) / total_criteria

print(lambda_max)

5.382137277934705


## Menghitung Nilai Consistency Index (CI)

In [167]:
consistency_index = (lambda_max - total_criteria) / (total_criteria - 1)

print(consistency_index)

0.09553431948367619


## Perhitungan Consistency Ratio

In [168]:
consistency_ratio = consistency_index / 1.12

print(consistency_ratio)

0.08529849953899658


# Menghitung Perbandingan Pasangan untuk Setiap Alternatif/Pilihan pada Tiap Kriteria

## Pembuatan Tabel Perbandingan

## Proses Normalisasi Data

## Mengalikan Matriks dengan PW

## Menghitung Bobot Prioritas

## Menghitung Nilai $\lambda_{max}$

## Menghitung Nilai Consistency Index (CI)

# Menghitung Nilai Consistency Ratio (CR)

# Pengambilan Keputusan